### ISSUE TITLE
Can this be installed in an existing applications

### ISSUE THREAD

**Issue by precamp-io** [Jurager/teams#11]
This is an amazing piece of work. I have a prebuilt application with standard Laravel admin, owner and user permissions, can I install this without an major overhaul?

**Comment by Jurager** [comment]
@precamp-io I would recommend this package only if you have a real need to do complex user role management in a team. It is always easiest to use the package on a clean install, of course, but no one forbids you to use it already in a working project. In any case, you will have to rewrite some methods. You will have to make changes to your User and Teams models based on the ones in folder 'Stubs'. Of course, I recommend that you first check all this on a copy of the project

**Comment by jihadismail8** [comment]
so it can be used with jetstream ? or with breeze ? or it be used alone ?

**Comment by Jurager** [comment]
> so it can be used with jetstream ? or with breeze ? or it be used alone ?

You can use it as a separate package of course. You can also safely use it together with Breeze, since the package does not provide registration / authorization and does not intersect with the functionality of Breeze. 

Jetstream can be confusing. This package started as a fork of Jetstream's role-management part, but it has changed a lot since then. Now, they have little in common, though overlaps can still happen sometimes. In any case, we have not tested such integration.
