### ISSUE TITLE
Method $user->switchTeam() doesn't exist

### ISSUE THREAD

**Issue by jonagoldman** [Jurager/teams#21]
The method called in the `CreateTeam` action is not defined anywhere.

https://github.com/Jurager/teams/blob/48289efc5850a8d259a894c1c6b4c5a5b7ac0aee/stubs/app/Actions/Teams/CreateTeam.php#L32-L34

**Comment by Jurager** [comment]
@jonagoldman this seems like garbage from version 1.0, switching between commands was removed a long time ago, and it is not used anywhere else. Anyway, fixed in [https://github.com/Jurager/teams/commit/34c6a655b6482fff9923bbe57491e76c5138ae57](https://github.com/Jurager/teams/commit/34c6a655b6482fff9923bbe57491e76c5138ae57). Thanks!
